#config:
#  email:
#    mail-a:
#      from: from@mail.com
#      to: to_1@mail.com,to_2@mail.com
#      cc: cc@mail.com
#      bcc: bcc@mail.com
#      subject: 'Mail Subject'
#      body-template: 'body-template.html'
#    mail-b:
#      from: from@mail.com
#      to: to_1@mail.com,to_2@mail.com
#      cc: cc@mail.com
#      bcc: bcc@mail.com
#      subject: 'Mail Subject'
#      body-template: 'body-template.html'
#
#api:
#  notification:
#    base-url: https://xxx.yyy.zzz/notification
#    endpoints:
#      send-email: ${api.notification.base-url}/api/v2/email
